version: "3.9"

services:
  app:
    container_name: zzlabs-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npx ts-node-dev --respawn --transpile-only src/index.ts
    env_file:
      - .env
