name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npx tsc

      - name: Restart or Start PM2 process
        run: pm2 describe zzlabs-api && pm2 restart zzlabs-api || pm2 start dist/index.js --name zzlabs-api --watch
