name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code in real folder
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          git pull origin main

      - name: Install dependencies
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          npm install

      - name: Build TypeScript
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          npx tsc

      - name: Restart or Start PM2 process
        run: |
          pm2 describe zzlabs-api && pm2 restart zzlabs-api || pm2 start /home/ubuntu/zzlabs-api-test-server/dist/index.js --name zzlabs-api --watch
