name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Asegurarse de estar en la carpeta correcta y traer los últimos cambios
      - name: Reset working directory to latest commit
        working-directory: /home/ubuntu/zzlabs-api-test-server
        run: |
          git fetch origin
          git reset --hard origin/main

      # 2️⃣ Crear el archivo .env a partir de los GitHub Secrets
      - name: Create .env from GitHub Secrets
        working-directory: /home/ubuntu/zzlabs-api-test-server
        run: |
          echo "TEST_SECRET=${{ secrets.TEST_SECRET }}" >> .env
          # Añade aquí más secretos si los necesitás

      # 3️⃣ Construir y levantar los contenedores con Docker Compose
      - name: Build and run Docker container
        working-directory: /home/ubuntu/zzlabs-api-test-server
        run: make up
