name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code in real folder
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          git pull origin main

      - name: Clean old .env and pull latest code
        working-directory: /home/ubuntu/zzlabs-api-test-server
        run: |
          rm -f .env
          git pull origin main

      - name: Create .env file from GH secrets
        working-directory: /home/ubuntu/zzlabs-api-test-server
        run: |
          echo "TEST_SECRET=${{ secrets.TEST_SECRET }}" > .env

      - name: Build Docker image
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          docker compose build

      - name: Run Docker container
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          run: make up
