name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy app locally on EC2
        run: |
          cd ~/simple-test-node-server
          git pull
          npm install
          npx tsc
          pm2 restart simple-test-node-server
