name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code in real folder
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          git pull origin main

      - name: Build Docker image
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          docker compose build

      - name: Run Docker container
        run: |
          cd /home/ubuntu/zzlabs-api-test-server
          docker compose down
          docker compose up -d
